# conda env create --file environment.yml
name: {{cookiecutter.project_slug.lower()}}
channels:
  - conda-forge
  - defaults
dependencies:
  - python={{cookiecutter.python_version}}
  - pip
  - pandas 
  - numpy
  - matplotlib
  - seaborn
  {%if cookiecutter.project_packages == "all" -%}
  - fs
  - jupyter
  - jupyterlab
  - pathlib
  {%endif -%}
